### ISSUE TITLE
Other way of download the model

### ISSUE THREAD

**Issue by StarsTesla** [PJLab-ADG/OASim#2]
The Baidu cloud disk is so fxxk slow.

**Comment by amoghskanda** [comment]
can you upload the model to onedrive?baidu cloud is not loading at all

**Comment by amoghskanda** [comment]
@StarsTesla how did you endup downloading the model? Did you have to download Baidu_Netdisk.exe or what?

**Comment by StarsTesla** [comment]
@amoghskanda I didnt, I found this will OOM on my 3060, and this repo seems not provide the code of realscene like waymo .
